name: Auto-Update
permissions:
  contents: write
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: update subs
      run: |
        curl -s -L https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/Splitted-By-Protocol/vless.txt | base64 -d | head -n 250 > vless.txt
        cat vless.txt
    - name: commit
      run: |
        git config --global user.email github-actions-bot@github.com
        git config --global user.name "github-actions-bot"
        git add .
        git commit -am "chore: auto update by github-action"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
